apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: quotopia
roleRef:
  kind: ClusterRole
  name: job-reader
  apiGroup: rbac.authorization.k8s.io
